-- ============================================================
-- SEED: deck kuis & latihan mendengar
--   1. Latihan Mendengar  — 5 level, dari 1 kalimat sederhana
--      sampai cerita pendek dengan pertanyaan tersirat
--   2. Uji Diri: AI Engineering — kuis berjawaban, 3 subtopik
--
-- WAJIB jalankan migration 00006_card_formats.sql (lalu 00007) lebih dulu,
-- di eksekusi terpisah (nilai enum baru belum bisa dipakai di
-- transaksi yang sama dengan pembuatannya).
--
-- File ini dibuat dari skrip; isi `details` mengikuti bentuk
-- CardDetails di packages/types/src/database.ts.
-- ============================================================

-- Latihan Mendengar
INSERT INTO categories (id, slug, name, description, is_free, sort_order, theme, mode) VALUES
  ('33333333-3333-3333-3333-333333333333', 'latihan-mendengar', 'Latihan Mendengar', 'Latih konsentrasi dan daya simak anak. Satu orang membacakan, yang lain menjawab — level naik dari satu kalimat sederhana sampai cerita pendek.', true, 3, 'sky', 'mendengar');
INSERT INTO sections (id, category_id, slug, name, description, icon, sort_order) VALUES
  ('cccc0001-0000-0000-0000-000000000001', '33333333-3333-3333-3333-333333333333', 'level-1', 'Level 1 — Siapa & Apa', 'Satu kalimat, satu tokoh, satu kejadian.', '1️⃣', 1),
  ('cccc0002-0000-0000-0000-000000000002', '33333333-3333-3333-3333-333333333333', 'level-2', 'Level 2 — Di Mana & Kapan', 'Ada keterangan tempat dan waktu.', '2️⃣', 2),
  ('cccc0003-0000-0000-0000-000000000003', '33333333-3333-3333-3333-333333333333', 'level-3', 'Level 3 — Urutan & Detail', 'Dua sampai tiga kejadian berurutan, plus detail warna atau jumlah.', '3️⃣', 3),
  ('cccc0004-0000-0000-0000-000000000004', '33333333-3333-3333-3333-333333333333', 'level-4', 'Level 4 — Sebab & Akibat', 'Ada kata "karena", "lalu", atau "sehingga". Wajib ada pertanyaan mengapa.', '4️⃣', 4),
  ('cccc0005-0000-0000-0000-000000000005', '33333333-3333-3333-3333-333333333333', 'level-5', 'Level 5 — Cerita & Kesimpulan', 'Cerita pendek dengan beberapa tokoh. Ada jawaban yang harus disimpulkan sendiri.', '5️⃣', 5);
INSERT INTO cards (section_id, card_type, difficulty, level, content_text, details, sort_order, is_free_preview) VALUES
  ('cccc0001-0000-0000-0000-000000000001', 'listening', 'easy', 1, 'Budi makan apel merah.', '{"questions": [{"question": "Siapa yang makan?", "answer": "Budi"}, {"question": "Apa yang dimakan Budi?", "answer": "Apel merah"}]}'::jsonb, 1, true),
  ('cccc0001-0000-0000-0000-000000000001', 'listening', 'easy', 1, 'Kucing tidur di atas kursi.', '{"questions": [{"question": "Hewan apa yang tidur?", "answer": "Kucing"}, {"question": "Kucing tidur di mana?", "answer": "Di atas kursi"}]}'::jsonb, 2, true),
  ('cccc0001-0000-0000-0000-000000000001', 'listening', 'easy', 1, 'Ibu memasak nasi goreng.', '{"questions": [{"question": "Siapa yang memasak?", "answer": "Ibu"}, {"question": "Apa yang dimasak Ibu?", "answer": "Nasi goreng"}]}'::jsonb, 3, false),
  ('cccc0002-0000-0000-0000-000000000002', 'listening', 'easy', 2, 'Pagi ini Sari menyiram bunga di halaman rumah.', '{"questions": [{"question": "Kapan Sari menyiram bunga?", "answer": "Pagi ini"}, {"question": "Di mana Sari menyiram bunga?", "answer": "Di halaman rumah"}, {"question": "Apa yang dilakukan Sari?", "answer": "Menyiram bunga"}]}'::jsonb, 1, true),
  ('cccc0002-0000-0000-0000-000000000002', 'listening', 'easy', 2, 'Setiap sore Ayah bermain bola bersama Adi di lapangan.', '{"questions": [{"question": "Kapan mereka bermain bola?", "answer": "Setiap sore"}, {"question": "Di mana mereka bermain?", "answer": "Di lapangan"}, {"question": "Ayah bermain bersama siapa?", "answer": "Adi"}]}'::jsonb, 2, true),
  ('cccc0002-0000-0000-0000-000000000002', 'listening', 'easy', 2, 'Hari Jumat, Nenek datang ke rumah membawa kue.', '{"questions": [{"question": "Hari apa Nenek datang?", "answer": "Hari Jumat"}, {"question": "Apa yang dibawa Nenek?", "answer": "Kue"}]}'::jsonb, 3, false),
  ('cccc0003-0000-0000-0000-000000000003', 'listening', 'medium', 3, 'Dodi memakai sepatu biru, mengambil tas, lalu berjalan ke sekolah bersama dua temannya.', '{"questions": [{"question": "Apa warna sepatu Dodi?", "answer": "Biru"}, {"question": "Apa yang Dodi lakukan setelah memakai sepatu?", "answer": "Mengambil tas"}, {"question": "Dodi berjalan bersama berapa teman?", "answer": "Dua teman"}]}'::jsonb, 1, true),
  ('cccc0003-0000-0000-0000-000000000003', 'listening', 'medium', 3, 'Lina membeli tiga buku dan satu pensil hijau, lalu membayarnya ke kasir.', '{"questions": [{"question": "Berapa buku yang dibeli Lina?", "answer": "Tiga buku"}, {"question": "Apa warna pensilnya?", "answer": "Hijau"}, {"question": "Apa yang Lina lakukan terakhir?", "answer": "Membayar ke kasir"}]}'::jsonb, 2, true),
  ('cccc0003-0000-0000-0000-000000000003', 'listening', 'medium', 3, 'Setelah salat Subuh, Fajar merapikan tempat tidur, mandi, lalu sarapan roti dengan susu.', '{"questions": [{"question": "Apa yang Fajar lakukan pertama kali setelah salat?", "answer": "Merapikan tempat tidur"}, {"question": "Apa yang Fajar makan saat sarapan?", "answer": "Roti dengan susu"}, {"question": "Fajar mandi sebelum atau sesudah sarapan?", "answer": "Sebelum sarapan"}]}'::jsonb, 3, false),
  ('cccc0004-0000-0000-0000-000000000004', 'listening', 'hard', 4, 'Karena ban sepeda kempis, Rara memutuskan untuk naik bus, lalu pergi ke pusat kegiatan anak.', '{"questions": [{"question": "Apa yang terjadi?", "answer": "Ban sepeda Rara kempis"}, {"question": "Siapa yang membuat keputusan?", "answer": "Rara"}, {"question": "Apa yang diputuskan Rara?", "answer": "Naik bus"}, {"question": "Mengapa Rara melakukan itu?", "answer": "Karena ban sepedanya kempis"}]}'::jsonb, 1, true),
  ('cccc0004-0000-0000-0000-000000000004', 'listening', 'hard', 4, 'Hujan turun deras sehingga lapangan becek, jadi Pak Guru memindahkan pelajaran olahraga ke aula.', '{"questions": [{"question": "Mengapa lapangan becek?", "answer": "Karena hujan turun deras"}, {"question": "Ke mana pelajaran olahraga dipindahkan?", "answer": "Ke aula"}, {"question": "Mengapa pelajaran olahraga dipindahkan?", "answer": "Karena lapangannya becek"}]}'::jsonb, 2, true),
  ('cccc0004-0000-0000-0000-000000000004', 'listening', 'hard', 4, 'Andi lupa membawa bekal, lalu Bima membagi separuh rotinya karena kasihan melihat Andi lapar.', '{"questions": [{"question": "Apa yang Andi lupa bawa?", "answer": "Bekal"}, {"question": "Apa yang dilakukan Bima?", "answer": "Membagi separuh rotinya"}, {"question": "Mengapa Bima melakukan itu?", "answer": "Karena kasihan melihat Andi lapar"}]}'::jsonb, 3, false),
  ('cccc0005-0000-0000-0000-000000000005', 'listening', 'hard', 5, 'Hujan turun deras sore itu. Nina menunggu di depan sekolah, tapi ayahnya belum datang. Bu Guru lalu meminjamkan payung dan menemani Nina sampai ayahnya tiba. Nina tersenyum dan berterima kasih.', '{"questions": [{"question": "Kenapa Nina harus menunggu?", "answer": "Ayahnya belum datang menjemput"}, {"question": "Apa yang dilakukan Bu Guru?", "answer": "Meminjamkan payung dan menemani Nina"}, {"question": "Bagaimana perasaan Nina di akhir cerita? Dari mana kamu tahu?", "answer": "Senang atau lega — Nina tersenyum dan berterima kasih"}], "explanation": "Pertanyaan terakhir jawabannya tersirat: tidak disebut langsung, harus disimpulkan dari tindakan Nina."}'::jsonb, 1, true),
  ('cccc0005-0000-0000-0000-000000000005', 'listening', 'hard', 5, 'Raka dan Tio sama-sama ingin memakai ayunan. Raka bilang, "Kamu duluan saja, nanti gantian ya." Tio mengangguk. Setelah sepuluh hitungan, Tio turun dan Raka naik. Mereka bermain sampai sore.', '{"questions": [{"question": "Apa masalah Raka dan Tio?", "answer": "Sama-sama ingin memakai ayunan"}, {"question": "Bagaimana cara mereka menyelesaikannya?", "answer": "Bergantian, Tio duluan"}, {"question": "Sifat baik apa yang ditunjukkan Raka?", "answer": "Mau mengalah dan berbagi"}], "explanation": "Sifat Raka tidak disebut langsung — disimpulkan dari ucapannya."}'::jsonb, 2, true),
  ('cccc0005-0000-0000-0000-000000000005', 'listening', 'hard', 5, 'Ibu menaruh kue di meja untuk tamu. Adik melihatnya dan ingin mengambil satu. Kakak berkata, "Tunggu dulu, tanya Ibu." Adik pun bertanya. Ibu tersenyum dan memberi Adik satu kue dari dapur.', '{"questions": [{"question": "Untuk siapa kue di meja itu?", "answer": "Untuk tamu"}, {"question": "Apa yang dilakukan Adik setelah dinasihati Kakak?", "answer": "Bertanya dulu ke Ibu"}, {"question": "Menurutmu, kenapa Ibu memberi kue dari dapur, bukan dari meja?", "answer": "Karena kue di meja untuk tamu"}], "explanation": "Pertanyaan ketiga melatih menyimpulkan dari detail di awal cerita."}'::jsonb, 3, false);

-- Uji Diri: AI Engineering
INSERT INTO categories (id, slug, name, description, is_free, sort_order, theme, mode) VALUES
  ('44444444-4444-4444-4444-444444444444', 'uji-diri-ai-engineering', 'Uji Diri: AI Engineering', 'Kuis untuk menguji pemahaman membangun aplikasi berbasis LLM — dari konsep dasar, RAG, sampai agent dan evaluasi. Jawab dulu, lalu balik kartunya.', true, 4, 'indigo', 'kuis');
INSERT INTO sections (id, category_id, slug, name, description, icon, sort_order) VALUES
  ('dddd0001-0000-0000-0000-000000000001', '44444444-4444-4444-4444-444444444444', 'dasar-llm', 'Dasar LLM', 'Token, context window, prompt, dan parameter sampling.', '🧩', 1),
  ('dddd0002-0000-0000-0000-000000000002', '44444444-4444-4444-4444-444444444444', 'rag', 'RAG & Retrieval', 'Membuat model menjawab dari dokumenmu sendiri.', '📚', 2),
  ('dddd0003-0000-0000-0000-000000000003', '44444444-4444-4444-4444-444444444444', 'agent-evaluasi', 'Agent, Keamanan & Evaluasi', 'Tool use, prompt injection, dan cara mengukur kualitas.', '🛠️', 3);
INSERT INTO cards (section_id, card_type, difficulty, level, content_text, details, sort_order, is_free_preview) VALUES
  ('dddd0001-0000-0000-0000-000000000001', 'quiz', 'easy', 1, 'Apa itu token dalam konteks LLM?', '{"answer": "Potongan teks — bisa kata, bagian kata, atau tanda baca — yang diproses model.", "explanation": "Panjang input, output, dan biaya API dihitung dalam token, bukan kata atau karakter."}'::jsonb, 1, true),
  ('dddd0001-0000-0000-0000-000000000001', 'quiz', 'easy', 1, 'Apa yang dimaksud dengan context window?', '{"answer": "Jumlah maksimum token yang bisa diproses model dalam satu panggilan, termasuk input dan output."}'::jsonb, 2, true),
  ('dddd0001-0000-0000-0000-000000000001', 'true_false', 'easy', 2, 'Menaikkan temperature membuat jawaban model lebih akurat.', '{"isTrue": false, "explanation": "Temperature mengatur seberapa acak pemilihan token. Nilai rendah membuat output lebih konsisten; nilai tinggi lebih bervariasi, bukan lebih akurat."}'::jsonb, 3, false),
  ('dddd0001-0000-0000-0000-000000000001', 'multiple_choice', 'easy', 2, 'Kenapa LLM bisa “berhalusinasi”?', '{"options": ["Karena servernya kelebihan beban", "Karena model memprediksi teks yang terdengar masuk akal, bukan mengecek fakta", "Karena prompt-nya terlalu pendek", "Karena temperature selalu nol"], "correctIndex": 1, "explanation": "Model dilatih untuk menghasilkan kelanjutan teks yang paling mungkin. Tanpa sumber yang bisa dirujuk, ia bisa menyusun jawaban yang meyakinkan tapi salah."}'::jsonb, 4, false),
  ('dddd0001-0000-0000-0000-000000000001', 'clue', 'easy', 2, 'Teknik prompt apa ini?', '{"clues": ["Aku dipakai di dalam prompt.", "Aku berisi beberapa contoh pasangan input dan output.", "Model meniru pola dari contoh-contohku."], "answer": "Few-shot prompting"}'::jsonb, 5, false),
  ('dddd0001-0000-0000-0000-000000000001', 'multiple_choice', 'medium', 3, 'Kamu butuh output JSON yang selalu valid dari model. Cara paling andal?', '{"options": ["Menulis “tolong balas JSON” di akhir prompt", "Menurunkan temperature ke 0", "Memakai fitur structured output / JSON schema dari API", "Memperpanjang system prompt"], "correctIndex": 2, "explanation": "Structured output membatasi model agar hanya menghasilkan JSON sesuai skema — instruksi teks saja masih bisa dilanggar."}'::jsonb, 6, false),
  ('dddd0002-0000-0000-0000-000000000002', 'quiz', 'easy', 2, 'Apa kepanjangan RAG dan apa intinya?', '{"answer": "Retrieval-Augmented Generation: ambil dokumen yang relevan dulu, lalu sertakan di prompt agar model menjawab berdasarkan dokumen itu."}'::jsonb, 1, true),
  ('dddd0002-0000-0000-0000-000000000002', 'quiz', 'easy', 2, 'Apa itu embedding?', '{"answer": "Representasi teks dalam bentuk vektor angka, di mana teks yang maknanya mirip punya vektor yang berdekatan.", "explanation": "Inilah yang membuat pencarian berdasarkan makna (semantic search) bisa dilakukan."}'::jsonb, 2, true),
  ('dddd0002-0000-0000-0000-000000000002', 'ordering', 'medium', 3, 'Urutkan alur pipeline RAG yang umum.', '{"items": ["Pecah dokumen menjadi potongan (chunk)", "Ubah tiap chunk menjadi embedding", "Simpan embedding di vector database", "Cari chunk yang paling mirip dengan pertanyaan user", "Masukkan chunk itu ke prompt dan minta model menjawab"]}'::jsonb, 3, false),
  ('dddd0002-0000-0000-0000-000000000002', 'multiple_choice', 'medium', 3, 'Model harus menjawab dari dokumen internal perusahaan yang berubah setiap minggu. Pendekatan paling cocok?', '{"options": ["Fine-tuning ulang setiap minggu", "RAG", "Prompt yang lebih panjang tanpa dokumen", "Menaikkan temperature"], "correctIndex": 1, "explanation": "RAG cukup memperbarui indeks dokumen. Fine-tuning lebih cocok untuk mengubah gaya atau perilaku, bukan menyuntikkan pengetahuan yang sering berubah."}'::jsonb, 4, false),
  ('dddd0002-0000-0000-0000-000000000002', 'true_false', 'hard', 4, 'Di RAG, chunk yang lebih besar selalu menghasilkan jawaban yang lebih baik.', '{"isTrue": false, "explanation": "Chunk terlalu besar membuat hasil pencarian kurang tepat dan memenuhi context window; terlalu kecil kehilangan konteks. Ukurannya perlu diuji."}'::jsonb, 5, false),
  ('dddd0002-0000-0000-0000-000000000002', 'quiz', 'hard', 4, 'Chatbot RAG-mu sering mengutip potongan yang tidak relevan. Sebutkan minimal tiga hal yang kamu periksa.', '{"answer": "Ukuran dan cara chunking, kualitas model embedding, jumlah top-k, penggunaan reranker, dan apakah query user perlu ditulis ulang dulu.", "explanation": "Ini masalah retrieval, bukan generation — perbaiki tahap pencariannya dulu sebelum mengubah prompt."}'::jsonb, 6, false),
  ('dddd0003-0000-0000-0000-000000000003', 'quiz', 'easy', 2, 'Apa itu tool use (function calling)?', '{"answer": "Kemampuan model meminta aplikasi menjalankan fungsi tertentu — misal cari data atau kirim email — lalu memakai hasilnya untuk melanjutkan jawaban."}'::jsonb, 1, true),
  ('dddd0003-0000-0000-0000-000000000003', 'clue', 'medium', 3, 'Serangan apa ini?', '{"clues": ["Aku bersembunyi di teks yang dibaca model.", "Aku bisa ada di halaman web, email, atau dokumen.", "Aku menyuruh model mengabaikan instruksi aslinya."], "answer": "Prompt injection", "explanation": "Pertahanannya berlapis: perlakukan konten luar sebagai data, batasi izin tool, dan minta konfirmasi untuk aksi berisiko."}'::jsonb, 2, true),
  ('dddd0003-0000-0000-0000-000000000003', 'ordering', 'medium', 3, 'Urutkan satu putaran agent loop.', '{"items": ["Model menerima tugas dan konteks", "Model memutuskan memanggil tool", "Aplikasi menjalankan tool dan mengembalikan hasilnya", "Model membaca hasil lalu memutuskan langkah berikutnya atau menjawab"]}'::jsonb, 3, false),
  ('dddd0003-0000-0000-0000-000000000003', 'true_false', 'medium', 3, 'Cara terbaik menilai kualitas aplikasi LLM adalah mencoba beberapa prompt secara manual.', '{"isTrue": false, "explanation": "Coba manual berguna di awal, tapi butuh evaluation set: kumpulan kasus uji dengan kriteria yang jelas, dijalankan ulang setiap kali prompt atau model berubah."}'::jsonb, 4, false),
  ('dddd0003-0000-0000-0000-000000000003', 'multiple_choice', 'hard', 4, 'Agent-mu terus memanggil tool yang sama berulang-ulang. Penyebab paling mungkin?', '{"options": ["Temperature terlalu rendah", "Hasil tool tidak memberi informasi yang dibutuhkan model untuk lanjut", "Context window terlalu besar", "Model terlalu baru"], "correctIndex": 1, "explanation": "Periksa apa yang dikembalikan tool: pesan error yang jelas dan hasil yang informatif membantu model berganti strategi. Batasi juga jumlah langkah maksimum."}'::jsonb, 5, false),
  ('dddd0003-0000-0000-0000-000000000003', 'quiz', 'hard', 5, 'Kamu merancang support bot untuk ribuan pengguna. Sebutkan tiga trade-off yang harus kamu timbang.', '{"answer": "Kualitas vs biaya per percakapan, latensi vs kedalaman penalaran, dan otomatisasi vs kapan harus dialihkan ke manusia — ditambah keamanan data pengguna.", "explanation": "Tidak ada jawaban tunggal; yang dinilai adalah kemampuan menyebut trade-off dan cara mengukurnya."}'::jsonb, 6, false);

